version: '3.12'
services:
  hokm-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hokm-bot
    env_file:
      - ./hokm_bot/.env
    volumes:
      - ./hokm_bot/database/:/code/hokm_bot/database/
    restart: unless-stopped
    command: [ "python", "main.py" ]
    mem_limit: 400m
    cpus: 0.5

volumes:
  groups_db_data:
    driver: local
